export type StatRow = { label: string; value: string | number };

type ShellStats = {
  spread: number;
  explLvl: number;
  explRad: number;
  explImpRadius: number;
  explImpStr: number;
  gravity: number;
  lifetime: number;
  ricochetPct: number;
  ricochetAngle: number;
  normalization: number;
  ignore: number;
  shrapnelType: string;
  fShrpCount: number;
  fShrpDamage: number;
  fShrpSpread: number;
  wShrpCount: number;
  wShrpDamage: number;
  wShrpSpread: number;
  fExplLvl: number;
  fExplRadius: number;
};

export type AutocannonShellType = "AP" | "HE";
export type CannonShellType = "APFSDS" | "HEAT" | "HE";
export type RocketCategory = "ATGM" | "Rocket" | "Bomb" | "Grenade";
export type RocketType = "RocketPods" | "Thermobaric";
export type AtgmType = "HEAT" | "HE";

const round = (value: number, decimals = 2) => {
  const factor = 10 ** decimals;
  return Math.round(value * factor) / factor;
};

const getBracket = (mm: number) => {
  if (mm <= 39) return 0;
  if (mm <= 45) return 1;
  return 2;
};

const toSheet = (stats: ShellStats, penetration: number): StatRow[] => [
  { label: "Spread", value: stats.spread },
  { label: "Expl. Lvl", value: stats.explLvl },
  { label: "Expl. Rad", value: stats.explRad },
  { label: "Expl. Imp. Radius", value: stats.explImpRadius },
  { label: "Expl. Imp. Str", value: stats.explImpStr },
  { label: "Gravity", value: stats.gravity },
  { label: "Lifetime", value: stats.lifetime },
  { label: "Projectile Type", value: "-" },
  { label: "Ricochet %", value: stats.ricochetPct },
  { label: "Ricochet Angle", value: stats.ricochetAngle },
  { label: "Normalization", value: stats.normalization },
  { label: "Penetration", value: penetration },
  { label: "Ignore Less Than", value: stats.ignore },
  { label: "Shrapnel Type", value: stats.shrapnelType },
  { label: "F. Shrp Count", value: stats.fShrpCount },
  { label: "F. Shrp Speed", value: 100 },
  { label: "F. Shrp Damage", value: stats.fShrpDamage },
  { label: "F. Shrp Spread", value: stats.fShrpSpread },
  { label: "W. Shrp Count", value: stats.wShrpCount },
  { label: "W. Shrp Speed", value: 100 },
  { label: "W. Shrp Damage", value: stats.wShrpDamage },
  { label: "W. Shrp Spread", value: stats.wShrpSpread },
  { label: "F. Expl. Lvl", value: stats.fExplLvl },
  { label: "F. Expl Radius", value: stats.fExplRadius },
];

export const generateAutocannonResults = (
  mm: number,
  shellType: AutocannonShellType,
  rpm: number,
): StatRow[] => {
  const b = getBracket(mm);
  if (shellType === "AP") {
    const penetration = rpm < 300 ? Math.round(mm / 10 - 1) : 0;
    const table: ShellStats[] = [
      {
        spread: 0.5,
        explLvl: 7,
        explRad: 0.1,
        explImpRadius: 0,
        explImpStr: 0,
        gravity: 10,
        lifetime: 15,
        ricochetPct: 0.3,
        ricochetAngle: 70,
        normalization: 5,
        ignore: 3,
        shrapnelType: "Little (Weak)",
        fShrpCount: 3,
        fShrpDamage: 25,
        fShrpSpread: 360,
        wShrpCount: 3,
        wShrpDamage: 50,
        wShrpSpread: 30,
        fExplLvl: 0,
        fExplRadius: 0,
      },
      {
        spread: 0.4,
        explLvl: 7,
        explRad: 0.1,
        explImpRadius: 0,
        explImpStr: 0,
        gravity: 10,
        lifetime: 15,
        ricochetPct: 0.3,
        ricochetAngle: 70,
        normalization: 5,
        ignore: 3,
        shrapnelType: "Normal",
        fShrpCount: 5,
        fShrpDamage: 25,
        fShrpSpread: 360,
        wShrpCount: 5,
        wShrpDamage: 50,
        wShrpSpread: 30,
        fExplLvl: 0,
        fExplRadius: 0,
      },
      {
        spread: 0.3,
        explLvl: 8,
        explRad: 0.1,
        explImpRadius: 0,
        explImpStr: 0,
        gravity: 10,
        lifetime: 20,
        ricochetPct: 0.3,
        ricochetAngle: 70,
        normalization: 5,
        ignore: 3,
        shrapnelType: "Normal",
        fShrpCount: 8,
        fShrpDamage: 25,
        fShrpSpread: 360,
        wShrpCount: 7,
        wShrpDamage: 50,
        wShrpSpread: 35,
        fExplLvl: 0,
        fExplRadius: 0,
      },
    ];
    return toSheet(table[b], penetration);
  }

  const shrapnel = Math.round(mm / 2.7);
  const table: ShellStats[] = [
    {
      spread: 0.5,
      explLvl: 3,
      explRad: 0.3,
      explImpRadius: 3,
      explImpStr: 150,
      gravity: 10,
      lifetime: 15,
      ricochetPct: 0.3,
      ricochetAngle: 80,
      normalization: 0,
      ignore: 1,
      shrapnelType: "Little",
      fShrpCount: shrapnel,
      fShrpDamage: 75,
      fShrpSpread: 360,
      wShrpCount: 0,
      wShrpDamage: 0,
      wShrpSpread: 45,
      fExplLvl: 0,
      fExplRadius: 0,
    },
    {
      spread: 0.4,
      explLvl: 3,
      explRad: 0.5,
      explImpRadius: 5,
      explImpStr: 300,
      gravity: 15,
      lifetime: 15,
      ricochetPct: 0.3,
      ricochetAngle: 80,
      normalization: 0,
      ignore: 1,
      shrapnelType: "Strong",
      fShrpCount: shrapnel,
      fShrpDamage: 75,
      fShrpSpread: 360,
      wShrpCount: 0,
      wShrpDamage: 0,
      wShrpSpread: 45,
      fExplLvl: 0,
      fExplRadius: 0,
    },
    {
      spread: 0.3,
      explLvl: 4,
      explRad: 0.5,
      explImpRadius: 7,
      explImpStr: 550,
      gravity: 15,
      lifetime: 20,
      ricochetPct: 0.3,
      ricochetAngle: 80,
      normalization: 0,
      ignore: 1,
      shrapnelType: "Strong",
      fShrpCount: shrapnel,
      fShrpDamage: 75,
      fShrpSpread: 360,
      wShrpCount: 0,
      wShrpDamage: 0,
      wShrpSpread: 45,
      fExplLvl: 0,
      fExplRadius: 0,
    },
  ];
  return toSheet(table[b], 0);
};

export const generateCannonResults = (
  mm: number,
  shellType: CannonShellType,
  realLifePenetration?: number,
): StatRow[] => {
  const b = mm <= 60 ? 0 : mm <= 80 ? 1 : mm <= 99 ? 2 : 3;
  if (shellType === "APFSDS") {
    const penetration = round((realLifePenetration ?? 0) * 0.02407);
    const table: ShellStats[] = [
      {
        spread: 0.2,
        explLvl: 7,
        explRad: 0.1,
        explImpRadius: 0,
        explImpStr: 0,
        gravity: 10,
        lifetime: 15,
        ricochetPct: 0.3,
        ricochetAngle: 73,
        normalization: 5,
        ignore: 3,
        shrapnelType: "Weak",
        fShrpCount: 5,
        fShrpDamage: 25,
        fShrpSpread: 360,
        wShrpCount: 7,
        wShrpDamage: 60,
        wShrpSpread: 35,
        fExplLvl: 0,
        fExplRadius: 0,
      },
      {
        spread: 0.2,
        explLvl: 8,
        explRad: 0.1,
        explImpRadius: 0,
        explImpStr: 0,
        gravity: 10,
        lifetime: 15,
        ricochetPct: 0.2,
        ricochetAngle: 73,
        normalization: 5,
        ignore: 3,
        shrapnelType: "Normal",
        fShrpCount: 5,
        fShrpDamage: 25,
        fShrpSpread: 360,
        wShrpCount: 11,
        wShrpDamage: 75,
        wShrpSpread: 35,
        fExplLvl: 3,
        fExplRadius: 0.3,
      },
      {
        spread: 0.2,
        explLvl: 9,
        explRad: 0.1,
        explImpRadius: 0,
        explImpStr: 0,
        gravity: 10,
        lifetime: 20,
        ricochetPct: 0.2,
        ricochetAngle: 73,
        normalization: 5,
        ignore: 3,
        shrapnelType: "Normal",
        fShrpCount: 6,
        fShrpDamage: 25,
        fShrpSpread: 360,
        wShrpCount: 12,
        wShrpDamage: 75,
        wShrpSpread: 45,
        fExplLvl: 3,
        fExplRadius: 0.3,
      },
      {
        spread: 0.1,
        explLvl: 50,
        explRad: 0.1,
        explImpRadius: 0,
        explImpStr: 0,
        gravity: 10,
        lifetime: 20,
        ricochetPct: 0.2,
        ricochetAngle: 73,
        normalization: 5,
        ignore: 2,
        shrapnelType: "Strong",
        fShrpCount: 8,
        fShrpDamage: 25,
        fShrpSpread: 360,
        wShrpCount: 14,
        wShrpDamage: 80,
        wShrpSpread: 50,
        fExplLvl: 4,
        fExplRadius: 0.4,
      },
    ];
    return toSheet(table[b], penetration);
  }
  if (shellType === "HEAT") {
    const penetration = round(mm / (mm >= 81 ? 13 : 14));
    const table: ShellStats[] = [
      {
        spread: 0.2,
        explLvl: 6,
        explRad: 0.1,
        explImpRadius: 5,
        explImpStr: 500,
        gravity: 15,
        lifetime: 15,
        ricochetPct: 0.3,
        ricochetAngle: 80,
        normalization: 4,
        ignore: 2,
        shrapnelType: "Normal",
        fShrpCount: 20,
        fShrpDamage: 50,
        fShrpSpread: 360,
        wShrpCount: 3,
        wShrpDamage: 50,
        wShrpSpread: 8,
        fExplLvl: 0,
        fExplRadius: 0,
      },
      {
        spread: 0.2,
        explLvl: 7,
        explRad: 0.1,
        explImpRadius: 6,
        explImpStr: 1000,
        gravity: 15,
        lifetime: 15,
        ricochetPct: 0.3,
        ricochetAngle: 80,
        normalization: 4,
        ignore: 2,
        shrapnelType: "Normal",
        fShrpCount: 25,
        fShrpDamage: 70,
        fShrpSpread: 360,
        wShrpCount: 4,
        wShrpDamage: 60,
        wShrpSpread: 8,
        fExplLvl: 0,
        fExplRadius: 0,
      },
      {
        spread: 0.2,
        explLvl: 8,
        explRad: 0.1,
        explImpRadius: 7,
        explImpStr: 1000,
        gravity: 15,
        lifetime: 20,
        ricochetPct: 0.3,
        ricochetAngle: 80,
        normalization: 4,
        ignore: 2,
        shrapnelType: "Normal",
        fShrpCount: 30,
        fShrpDamage: 75,
        fShrpSpread: 360,
        wShrpCount: 5,
        wShrpDamage: 60,
        wShrpSpread: 10,
        fExplLvl: 0,
        fExplRadius: 0,
      },
      {
        spread: 0.2,
        explLvl: 50,
        explRad: 0.1,
        explImpRadius: 8,
        explImpStr: 1000,
        gravity: 15,
        lifetime: 20,
        ricochetPct: 0.3,
        ricochetAngle: 80,
        normalization: 4,
        ignore: 2,
        shrapnelType: "Strong",
        fShrpCount: 40,
        fShrpDamage: 80,
        fShrpSpread: 360,
        wShrpCount: 6,
        wShrpDamage: 65,
        wShrpSpread: 12,
        fExplLvl: 0,
        fExplRadius: 0,
      },
    ];
    return toSheet(table[b], penetration);
  }
  const shrapnel =
    mm >= 100 ? Math.round(mm / 1.2) : mm >= 81 ? Math.round(mm / 1.1) : mm;
  const table: ShellStats[] = [
    {
      spread: 0.2,
      explLvl: 5,
      explRad: 0.3,
      explImpRadius: 7,
      explImpStr: 750,
      gravity: 20,
      lifetime: 15,
      ricochetPct: 0.3,
      ricochetAngle: 85,
      normalization: 0,
      ignore: 1,
      shrapnelType: "Strong",
      fShrpCount: shrapnel,
      fShrpDamage: 75,
      fShrpSpread: 360,
      wShrpCount: 0,
      wShrpDamage: 0,
      wShrpSpread: 45,
      fExplLvl: 0,
      fExplRadius: 0,
    },
    {
      spread: 0.2,
      explLvl: 5,
      explRad: 0.5,
      explImpRadius: 8,
      explImpStr: 1250,
      gravity: 20,
      lifetime: 15,
      ricochetPct: 0.3,
      ricochetAngle: 85,
      normalization: 0,
      ignore: 1,
      shrapnelType: "Strong",
      fShrpCount: shrapnel,
      fShrpDamage: 80,
      fShrpSpread: 360,
      wShrpCount: 0,
      wShrpDamage: 0,
      wShrpSpread: 45,
      fExplLvl: 0,
      fExplRadius: 0,
    },
    {
      spread: 0.2,
      explLvl: 5,
      explRad: 0.7,
      explImpRadius: 9,
      explImpStr: 1500,
      gravity: 20,
      lifetime: 20,
      ricochetPct: 0.3,
      ricochetAngle: 85,
      normalization: 0,
      ignore: 1,
      shrapnelType: "Strong",
      fShrpCount: shrapnel,
      fShrpDamage: 90,
      fShrpSpread: 360,
      wShrpCount: 0,
      wShrpDamage: 0,
      wShrpSpread: 45,
      fExplLvl: 0,
      fExplRadius: 0,
    },
    {
      spread: 0.2,
      explLvl: 5,
      explRad: 1,
      explImpRadius: 10,
      explImpStr: 1500,
      gravity: 20,
      lifetime: 20,
      ricochetPct: 0.3,
      ricochetAngle: 85,
      normalization: 0,
      ignore: 1,
      shrapnelType: "Strong",
      fShrpCount: shrapnel,
      fShrpDamage: 100,
      fShrpSpread: 360,
      wShrpCount: 0,
      wShrpDamage: 0,
      wShrpSpread: 45,
      fExplLvl: 0,
      fExplRadius: 0,
    },
  ];
  return toSheet(table[b], 0);
};

export const generateIndirectResults = (kg: number): StatRow[] => {
  const b = kg <= 5 ? 0 : kg <= 10 ? 1 : kg <= 15 ? 2 : kg <= 20 ? 3 : 4;
  const rows = [
    {
      Spread: 0.3,
      "Expl. Lvl": 10,
      "Expl. Rad": "0.8-1.5",
      "Expl. Imp. Radius": 10,
      "Expl. Imp. Str": 1000,
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: 0,
      "Ignore Less Than": 1,
      "Shrapnel Type": "Strong",
      "F. Shrp Count": 80,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 75,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0.2,
      "Expl. Lvl": 50,
      "Expl. Rad": "1.5-2.2",
      "Expl. Imp. Radius": 15,
      "Expl. Imp. Str": 1000,
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: 0,
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 100,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 85,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0.1,
      "Expl. Lvl": 50,
      "Expl. Rad": "2.2-2.9",
      "Expl. Imp. Radius": 15,
      "Expl. Imp. Str": 1500,
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: 0,
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 120,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0.1,
      "Expl. Lvl": 50,
      "Expl. Rad": "3.2-4.5",
      "Expl. Imp. Radius": 20,
      "Expl. Imp. Str": 2000,
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: 0,
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 165,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 2,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0.1,
      "Expl. Lvl": 50,
      "Expl. Rad": "4.5-5.5",
      "Expl. Imp. Radius": 20,
      "Expl. Imp. Str": 2000,
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: 0,
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 180,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 3,
      "F. Expl Radius": 0.3,
    },
  ][b];

  return Object.entries(rows).map(([label, value]) => ({ label, value }));
};

export const generateRocketBombResults = (
  category: RocketCategory,
  options: {
    atgmType?: AtgmType;
    rocketType?: RocketType;
    bombKg?: number;
    grenadeMm?: number;
  },
): StatRow[] => {
  const atgmMap = {
    HEAT: {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "0.1",
      "Expl. Imp. Radius": 5,
      "Expl. Imp. Str": 1000,
      Gravity: 0,
      Lifetime: "15",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 5,
      Penetration: "8-20",
      "Ignore Less Than": 2,
      "Shrapnel Type": "Strong",
      "F. Shrp Count": 20,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 50,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 10,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 75,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 3,
      "F. Expl Radius": 0.4,
    },
    HE: {
      Spread: 0,
      "Expl. Lvl": 5,
      "Expl. Rad": "0.8-1.25",
      "Expl. Imp. Radius": 10,
      "Expl. Imp. Str": 1500,
      Gravity: 0,
      Lifetime: "15",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 70,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
  } as const;
  const rocketMap = {
    RocketPods: {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "0.3",
      "Expl. Imp. Radius": 5,
      "Expl. Imp. Str": 500,
      Gravity: 10,
      Lifetime: "15",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Normal",
      "F. Shrp Count": 15,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 50,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    Thermobaric: {
      Spread: 0,
      "Expl. Lvl": 6,
      "Expl. Rad": "Depends",
      "Expl. Imp. Radius": 10,
      "Expl. Imp. Str": 1500,
      Gravity: 10,
      Lifetime: "15",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 50,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
  } as const;
  const bombKg = options.bombKg ?? 10;
  const bombIndex =
    bombKg <= 10
      ? 0
      : bombKg <= 50
        ? 1
        : bombKg <= 100
          ? 2
          : bombKg <= 250
            ? 3
            : bombKg <= 500
              ? 4
              : 5;
  const bombRows = [
    {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "0.3-1.4",
      "Expl. Imp. Radius": 5,
      "Expl. Imp. Str": 500,
      Gravity: 0,
      Lifetime: "0.01",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Strong",
      "F. Shrp Count": 15,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 50,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "1.6",
      "Expl. Imp. Radius": 10,
      "Expl. Imp. Str": 1000,
      Gravity: 0,
      Lifetime: "0.01",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Strong",
      "F. Shrp Count": 50,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 50,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "2.6",
      "Expl. Imp. Radius": 15,
      "Expl. Imp. Str": 1000,
      Gravity: 0,
      Lifetime: "0.01",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Strong",
      "F. Shrp Count": 70,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 80,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "5.8",
      "Expl. Imp. Radius": 15,
      "Expl. Imp. Str": 1500,
      Gravity: 0,
      Lifetime: "0.01",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 110,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "7.6",
      "Expl. Imp. Radius": 20,
      "Expl. Imp. Str": 2000,
      Gravity: 0,
      Lifetime: "0.01",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 140,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0,
      "Expl. Lvl": 50,
      "Expl. Rad": "10",
      "Expl. Imp. Radius": 25,
      "Expl. Imp. Str": 3000,
      Gravity: 0,
      Lifetime: "0.01",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "0",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 150,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
  ] as const;
  const grenadeMm = options.grenadeMm ?? 40;
  const grenadeIndex = grenadeMm < 40 ? 0 : grenadeMm === 40 ? 1 : 2;
  const grenadeRows = [
    {
      Spread: 0,
      "Expl. Lvl": 2,
      "Expl. Rad": "0.5",
      "Expl. Imp. Radius": 0,
      "Expl. Imp. Str": 100,
      Gravity: 0,
      Lifetime: "30",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "1",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 9,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0,
      "Expl. Lvl": 3,
      "Expl. Rad": "0.75",
      "Expl. Imp. Radius": 1,
      "Expl. Imp. Str": 100,
      Gravity: 0,
      Lifetime: "30",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "1",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 12,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
    {
      Spread: 0,
      "Expl. Lvl": 3,
      "Expl. Rad": "1",
      "Expl. Imp. Radius": 2,
      "Expl. Imp. Str": 100,
      Gravity: 0,
      Lifetime: "30",
      "Projectile Type": "-",
      "Ricochet %": 0,
      "Ricochet Angle": 90,
      Normalization: 0,
      Penetration: "1",
      "Ignore Less Than": 1,
      "Shrapnel Type": "Forceful",
      "F. Shrp Count": 14,
      "F. Shrp Speed": 200,
      "F. Shrp Damage": 100,
      "F. Shrp Spread": 360,
      "W. Shrp Count": 0,
      "W. Shrp Speed": 200,
      "W. Shrp Damage": 0,
      "W. Shrp Spread": 45,
      "F. Expl. Lvl": 0,
      "F. Expl Radius": 0,
    },
  ] as const;

  const selected =
    category === "ATGM"
      ? atgmMap[options.atgmType ?? "HEAT"]
      : category === "Rocket"
        ? rocketMap[options.rocketType ?? "RocketPods"]
        : category === "Bomb"
          ? bombRows[bombIndex]
          : grenadeRows[grenadeIndex];
  return Object.entries(selected).map(([label, value]) => ({ label, value }));
};
